# Generated by Django 5.0.6 on 2024-06-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
                ('last_login', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=255)),
                ('message_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('booked_date', models.DateField()),
                ('feedback', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.TimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_started', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_information', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.caregivercontact')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('medical_history', models.TextField()),
                ('preferred_language', models.CharField(max_length=50)),
                ('emergency_contacts', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.clientcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Communicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.admin')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.message')),
            ],
        ),
        migrations.CreateModel(
            name='Billed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.billing')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Receives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.caregiver')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.service')),
            ],
        ),
    ]
