# Generated by Django 5.0.6 on 2024-06-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomecareApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicates',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='communicates',
            name='message',
        ),
        migrations.RemoveField(
            model_name='provides',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='provides',
            name='service',
        ),
        migrations.RemoveField(
            model_name='receives',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='receives',
            name='service',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.AddField(
            model_name='billing',
            name='schedule',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='admin',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='caregiver',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.caregiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='availability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='contact_information',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='caregivercontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='caregivercontact',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emergency_contacts',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Billed',
        ),
        migrations.DeleteModel(
            name='Communicates',
        ),
        migrations.DeleteModel(
            name='Provides',
        ),
        migrations.DeleteModel(
            name='Receives',
        ),
    ]
