# Generated by Django 5.0.6 on 2024-06-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomecareApp', '0002_remove_communicates_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='contact_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomecareApp.caregivercontact'),
        ),
    ]
