# Generated by Django 5.0.6 on 2024-06-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomecareApp', '0003_alter_caregiver_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_info',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='HomecareApp.clientcontact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='HomecareApp.schedule'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='contact_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='HomecareApp.caregivercontact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emergency_contacts',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='HomecareApp.admin'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='HomecareApp.caregiver'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='HomecareApp.service'),
        ),
    ]
